### ISSUE TITLE
Getting vs Setting

### ISSUE THREAD

**Issue by bsaund** [UM-ARM-Lab/arc_utilities#10]
Why is the function named GetParams (and it does 'get' params from the server), but the logging says "Setting"?

https://github.com/UM-ARM-Lab/arc_utilities/blob/a01e97a1f523d901c6874f2b9845d752bc12cf19/include/arc_utilities/ros_helpers.hpp#L20-L25

**Comment by dmcconachie** [comment]
Originally this code was part of the SMMAP framework, in which it was actually setting local variables, based on params on the ROS master. We should probably change this wording, but I've not thought of a good alternative, perhaps `"Retrieved parameter " << param_name << " with value " << param_val"` but that seems unnecessarily wordy.

**Comment by dmcconachie** [comment]
Resolved in https://github.com/UM-ARM-Lab/arc_utilities/commit/ddfa5e305d71c648932980e692fb57b3bc4991ce
