### ISSUE TITLE
serialization_ros.hpp is redundant

### ISSUE THREAD

**Issue by dmcconachie** [UM-ARM-Lab/arc_utilities#22]
This functionality exists already in ros, we should probably remove this file and replace any usage of it with the ros versions. For example from SDF tools:
```
ros::serialization::IStream deser_stream(deser_buffer.get(), serialized_size);
sdf_tools::SDF new_message;
ros::serialization::deserialize(deser_stream, new_message);
```

**Comment by dmcconachie** [comment]
Per Calder: in some cases serialization in ROS differs from arc_utilities, so it should be documented. ROS uses 32 bit sizes, arc_utilities uses 64 bit sizes

**Comment by calderpg** [comment]
Our own serialization for basic ROS types should probably be maintained, since it is considerably more straightforward and simpler than ROS' own de/serialization system and easier to combine with our serialization scheme for non-ROS types.

**Comment by dmcconachie** [comment]
That's a very good point about integration with non-ROS datatypes, or multiple ROS messages. Will discuss with the others and likely end up leaving in this functionality.
