### ISSUE TITLE
 error: ‘evaluator’ is not a class template

### ISSUE THREAD

**Issue by sunbuny** [UM-ARM-Lab/arc_utilities#24]
I have a problem on building this project.

` error: ‘evaluator’ is not a class template
 struct evaluator<Aligned4Vector3<Scalar> >
        ^
`

**Comment by sunbuny** [comment]
Could you please help me to figure this out. Thank you.

**Comment by dmcconachie** [comment]
We'll need more details if we're going to be able to help. Are you trying to use `aligned_eigen_types.hpp`? Can you give us a minimum example of the problem?

**Comment by sunbuny** [comment]
I just clone the project, and catkin_make it. I changed the 

> #find_package(Eigen3 REQUIRED)
set(Eigen3_INCLUDE_DIRS /usr/include/eigen3)
to fix the problem of can't find eigen.
When the build finished, it came out the 
`In file included from /home/sun/ros_ws/deformable/src/arc_utilities/src/test_eigen_math.cpp:6:0:
/home/sun/ros_ws/deformable/src/arc_utilities/include/arc_utilities/aligned_eigen_types.hpp:214:8: error: ‘evaluator’ is not a class template
 struct evaluator<Aligned4Vector3<Scalar> >
        ^
make[2]: *** [arc_utilities/CMakeFiles/test_eigen_math.dir/src/test_eigen_math.cpp.o] Error 1
make[1]: *** [arc_utilities/CMakeFiles/test_eigen_math.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
`

**Comment by dmcconachie** [comment]
This particular part of arc_utilities has only been tested on Ubuntu 16.04, ROS Kinetic, GCC 5.4 and has no problems compiling on this combination. Are you using 14.04 and GCC 4.x? It looks like you are based on the problem with finding Eigen.

**Comment by dmcconachie** [comment]
We got a similar issue recently due to an incompatible Eigen version; someone had installed 3.2.8 into `/usr/local/include/eigen3` which was found before the default version of Eigen (3.3-beta (3.2.92) is in the 16.04 repos) in `/usr/include/eigen3`. So this may just be an Eigen version incompatibility.
