### ISSUE TITLE
Change `GridIndexToLocation` and `LocationToGridIndex` return types

### ISSUE THREAD

**Issue by calderpg** [UM-ARM-Lab/arc_utilities#29]
Functions `GridIndexToLocation` and `LocationToGridIndex` should change their return types to improve consistency.

`GridIndexToLocation` should change from `std::vector<double>` to `Eigen::Vector4d`

`LocationToGridIndex` should change from `std::vector<int64_t>` to `GRID_INDEX`

All uses in arc_utilities and sdf_tools should already check that these values are inside the grid boundaries already, so having these functions no longer perform bounds checking is not an issue.

**Comment by dmcconachie** [comment]
We should also change the input types (or add additional overloads) that accept the corresponding return type of the other function.

**Comment by calderpg** [comment]
I've started this change on my fork, and the disruption has been relatively limited. If y'all wait for me to merge in a version of the header->library changes we can get a whole bunch of these issues resolved in both ends and get both forks synced again.

**Comment by dmcconachie** [comment]
Works for me.
