### ISSUE TITLE
XBox controller triggers when controller is turned on

### ISSUE THREAD

**Issue by bsaund** [UM-ARM-Lab/arc_utilities#34]
When the xbox controller is turned on it triggers a ros message.

In Victor's stack, this causes the grippers to open.

Possible fix: Ignore the first message from the controller

**Comment by dmcconachie** [comment]
The concerns with Victor have been mostly addressed in https://github.com/UM-ARM-Lab/kuka_iiwa_interface/pull/91 . Do we still want more changes?
