### ISSUE TITLE
Switch to custom assert macro

### ISSUE THREAD

**Issue by a-price** [UM-ARM-Lab/arc_utilities#56]
For places where `assert` is used for tasks other than debugging/sanity checking, we should use custom assert macro that ignores `NDEBUG`. See https://github.com/UM-ARM-Lab/arc_utilities/pull/54#issuecomment-445986740

**Comment by bsaund** [comment]
Many of the `assert`s are really tests, and in such cases this issue can be resolved by moving to the gtest framework:
https://github.com/UM-ARM-Lab/arc_utilities/issues/55
