### ISSUE TITLE
List Dependencies

### ISSUE THREAD

**Issue by bsaund** [UM-ARM-Lab/arc_utilities#73]
What are arc_utilities dependencies? How do you install it?
Running into a few issues when installing on a fresh docker image:

`cannot find Eigen3.cmake`

`zlib.h: No such file or directory`

**Comment by dmcconachie** [comment]
`zlib.h` comes from `zlib1g-dev` according to dpkg

The `FindEigen.cmake` that is used here is I believe coming from `ros-kinetic-cmake-modules`

I've never installed either of these specifically; these files have always been available as part of a meta package, or some similar dependency chain.

**Comment by calderpg** [comment]
Depending on system and installed packages, `Eigen3` can be found from a cmake file installed by Eigen itself. `FindEigen` in `cmake-modules` is there for compatibility with older systems that didn't install the cmake file to the system and referred to it via `find_package(Eigen)`.

**Comment by bsaund** [comment]
https://github.com/UM-ARM-Lab/arc_utilities/pull/75

The Dockerfile from continuous integration from TravisCI shows how to build on a fresh system
