### ISSUE TITLE
Profiler tests occasionally failing on TravisCI

### ISSUE THREAD

**Issue by bsaund** [UM-ARM-Lab/arc_utilities#77]
Some of the profiler tests rely on timing. The TravisCI servers might be slow, so at least once the build has failed:
https://travis-ci.com/UM-ARM-Lab/arc_utilities/builds/106956715

Solution: Perhaps just remove these tests? Perhaps extend the time limit?

**Comment by a-price** [comment]
I think I get why
https://github.com/UM-ARM-Lab/arc_utilities/blob/e1b4c7e456f2071d8e54076462620cbe36fc3b40/tests/timings_tests.cpp#L65
should usually be true, but
https://github.com/UM-ARM-Lab/arc_utilities/blob/e1b4c7e456f2071d8e54076462620cbe36fc3b40/tests/timings_tests.cpp#L61
seems like a toss-up. Is the timer faster after its first call? Or should it be `t1_elapsed_restarted < t1_elapsed`?

**Comment by bsaund** [comment]
https://github.com/UM-ARM-Lab/arc_utilities/pull/78

**Comment by bsaund** [comment]
Tests passing now after PR. Will reopen if these tests fail in the future
